ooni/probe-desktop

renderer/pages/_document.js
Using `<title>` in `pages/_document.js` leads to unexpected results as per https://github.com/zeit/next.js/blob/master/errors/no-document-title.md
=> Remove page title from _document.js

renderer/components/Sidebar.js
Next.js 9 automatically prefetches components as they appear in viewport. Refer: https://err.sh/zeit/next.js/prefetch-true-deprecated
=> Remove deprecated prefetch attribute from Link

renderer/components/measurement/MeasurementContainer.js, renderer/components/nettests/index.js, renderer/components/nettests/websites/WebConnectivity.js
Implements 1 out of 7 views listed in #3
=> Implement skeleton for Test Details Views

main/utils/paths.js, package.json, scripts/download-bin.js
Includes some tweaks to the build script to allow for releases
that contain git tags. Removes support for downloading a CA
bundle, since probe-engine now manages that.
Companion to https://github.com/ooni/probe-cli/pull/65
=> Upgrade to ooni/probe-cli@v3.0.0-beta.4

main/windows/windowURL.js
This fixes the builds having a white page when loading.
=> Use the new next path for builds in production

main/windows/windowURL.js, renderer/pages/home.js
The descriptions are now in scrollable boxes.
Fixes (not really) #63 (Will close it when a proper solution is implemented)
=> Handle overflowing test card descriptions 

renderer/components/measurement/RawDataContainer.js
Makes the `Fixed` modal full width. Since the sidebar has a higher `z-index`, we avoid an overlap with it by adding a margin to the left of the modal.
Looks like this now:
=> Fix width of Raw Data modal

renderer/components/test-results/ResultRow.js
Fix alignment of icons and labels in Result list rows. Looks like this now:
=> Fix alignment of result list row summaries

renderer/components/ExternalLink.js, renderer/components/FormattedMarkdownMessage.js, renderer/components/onboard/Sections.js
Fixes #60 
Looks like this. Do we want to remove the underline from the link's default styling?
=> Add link to risks doc in onboarding screen

main/utils/ooni/ooniprobe.js
See https://github.com/ooni/probe-cli/pull/111 for documentation
on the design of killing ooniprobe portably.
Closes https://github.com/ooni/probe/issues/1005.
=> ooniprobe.js: kill ooniprobe by closing stdin

renderer/components/home/running.js
Fixes ooni/probe#988
Uses localized output from moment.js instead of the translation used by `probe-mobile`.
=> Fix duplicate ETA label for running tests

renderer/components/nettests/circumvention/Tor.js
Fixes ooni/probe#1007
Allows sorting the icons in columns showing connection status.
=> Use custom sorting function for tor connection status columns

renderer/components/measurement/MeasurementContainer.js, renderer/components/nettests/circumvention/Tor.js, renderer/components/nettests/websites/WebConnectivity.js
Fixes ooni/probe#959
Only the top header with back button and test name is sticky on the page.
@hellais maybe we should have a border or light shadow under the sticky
=> Unsticky Hero on measurement pages

renderer/components/ExternalLink.js, renderer/components/onboard/Sections.js
The gray on hover was added specifically for the link in the onboarding (2nd) screen which was white text on dark background. The `Link` component in `ooni-components` was updated later to use a themed blue as default color. It uses CSS `filter: brightness();` for hover, which doesn't work very well on white text, hence the [change to gray](https://github.com/ooni/probe-desktop/pull/111/files#diff-51c5bb6e90b2d6ecdaea6ca065fec954R108).
=> Revert to default colors for links on hover

renderer/components/HumanFilesize.js, renderer/components/test-results/TestResultsContainer.js, renderer/components/to-migrate/StatBox.js
Fixes ooni/probe#1045
Had to make some changes to layout to accommodate the larger data usage stats component. Looks like this now:
=> Fix alignment of data usage stats on results screen

.github/workflows/ci.yml, main/index.js, package.json, yarn.lock
Trivial upgrade. Seems to work well based on the basic tests written so far.
Replaced a couple of deprecated electron APIs
=> Upgrade electron and spectron

main/utils/ooni/ooniprobe.js
Fixes ooni/probe#1079
Uses `name` and `version` from `package.json`
=> Set software name and version to desktop

main/index.js
Fixes ooni/probe#1068
When `electron-updater` throws an error, we log it to Sentry in the `error` event handler.
=> Log to Sentry when autoUpdater thrown an error

renderer/components/Sidebar.js, renderer/pages/home.js
Fixes ooni/probe#1103
The fix was arrived after observing the DOM when using `<Text>` is used to wrap the `description` value which is generated by `FormattedMarkdownMessage`. When used as is `Text` component renders a `<p> ` tag which would then contain another `<p>` element rendered by `FormattedMarkdownMessage`. When rendered on server-side this somehow gets printed as
```
<p fontSizeApplied> // rendered by <Text />
</p>
<p> // rendered by <FormattedMarkdownMessage />
description
</p>
```
instead of
```
<p fontSizeApplied> <p> description text </p> </p>
```
which works when `<Text>` is rendered as a `<div>`
Also fixes the disappearing version label in the sidebar when client side JS gets activated.
=> Font size jump

main/index.js, main/windows/aboutWindow.js, renderer/pages/about.js
Fixes ooni/probe#1122
The `autoUpdater` system use the about window to show updates. The recent changes to manage focus of about window introduced a bug where duplicate windows were being created when `getFocus === false`. This is fixed in this PR.
Another change added here is to not focus the about window every time it is referenced. It still launches the window in the background, which I think is only better than popping it up to the user.
Maybe we should decouple the about window and the updater log view.
=> Fix about window problems

main/index.js
Skips popping up about window to notify 'update (not) avaialble'
=> Avoid unnecessary about window popup

renderer/pages/about.js
Fixes ooni/probe#1116
This wasn't a problem in Linux but was reproducible in Windows. @hellais can you test this in Mac please?
=> Break long paths in about window debug section

renderer/components/onboard/QuizSteps.js
Fixes ooni/probe#1196
By default `<Lottie>`﻿ allows click to pause the animation. This PR changes
the default behaviour to disable the pause on click.
=> Disable animation pause on click during onboarding

CHANGELOG.md, main/index.js, package.json, renderer/components/home/running.js
probe-cli: 3.0.3
* Fix missing auto update notice in about window (ooni/probe#1184)
* Fix logic in looking for informed consent in config file (ooni/probe#1188)
* Fix long paths in about window debug section (ooni/probe#1116)
* Fix missing translation string in when stopping a test (ooni/probe#1204)
* Disable pausing of animation during onboarding quiz (ooni/probe#1196)
* Removed styling of bootstrap time unit in Psiphon measurement details
* Bump websocket-extensions from 0.1.3 to 0.1.4 [dependabot]
* Bumped `electron-builder` to `22.7.0`
* Bumped `electron-updater` to `4.3.1`
﻿
=> Release 3.0.3

renderer/components/Modal.js, renderer/components/home/StopTestModal.js, renderer/components/home/running.js, renderer/components/onboard/QuizSteps.js, renderer/pages/home.js
Fixes ooni/probe#1205
I used the same style we use in the onboarding screens. I tried using the buttons from our design system, but dropped it later.
Also fixes the bug where the currently running test name wasn't being shown.
=> Show confirmation dialog before stopping test

scripts/download-bin.js
Spotted while doing a review for https://github.com/ooni/probe/issues/1218
=> fix(scripts/download-bin.js): don't download the zip archive

renderer/components/HumanFilesize.js, renderer/components/TwoColumnTable.js, renderer/components/result/ResultContainer.js
Fixes ooni/probe#1043
spacing between icons and labels.
Also went ahead and increased the vertical spacing between the rows. The screen looks like this.
=> Fix spacing and alignment of result overview contents

CHANGELOG.md, Readme.md, package.json, scripts/notarize.js
Updated version to `3.0.4-rc.1` to test before release. We will bump it to `3.0.4` after we some internal testing and then tag it for the release build to publish.
Tracking issue: https://github.com/ooni/ooni.org/issues/600
=> Release 3.0.4

main/ipcBindings.js, main/utils/config.js, main/utils/ooni/onboard.js, renderer/pages/onboard.js, renderer/pages/settings.js
At end of onboarding when 'Change defaults' is clicked, we set the config to opt-out of analytics. Problem with letting the user perform the change action is that a config file is already written by then and it would have 'opted-in' to allow the user to opt-out and then stands the risk of staying opted-in if the app is closed or navigated away. We should discuss if this is how we want to do this.
=> Change default values at end of onboarding process

main/index.js, main/windows/index.js
Currently, when the app window is closed, it doesn't quit and shows active in the dock. When clicked, it doesn't show the app. This fix completes this behavior by creating and showing the window.
Additionally, it also implements the single instance restriction as recommended by [electron docs](https://www.electronjs.org/docs/api/app?q=unhandled#apprequestsingleinstancelock).
=> Restore window on MacOS when activated from dock

main/utils/ooni/ooniprobe.js, package.json
Fixes ooni/probe#1425
* Revert the swapping of stdout and stderr when talking to probe-cli
* This build also runs Signal tests and shows the results and measurements properly.
Release notes for probe-cli@3.9.0](https://github.com/ooni/probe-cli/releases/tag/v3.9.0)
=> chore: use ooni/probe-cli 3.9.0

renderer/components/dashboard/URL.js
There are a couple of changes proposed in this PR: 
1. `validateURL` function has been shifted up so that it is declared first before a reference to it is made. I was getting error in `jest` that said a reference to the function was made before it was declared.
2. The condition that URL fields need to be dirty before calling the validation function has been removed. Now any change that happens to the textbox is validated.
The reason for this change is because of unexpected behavior arising in presence of this condition.
* The `Run` button would not enable unless focus was shifted to some other element in a headful environment. In a headless environment, the button wouldn't enable at all.
* Validation would not trigger unless focus was shifted to some other element.
The behavior is …
=> [Fix] Input URL fields need not be dirty for validation

Readme.md, package.json, scripts/download-bin.js
This diff changes ooniprobe-desktop to use cli v3.11.0-beta.2.
This cli release includes changes in the last (at this point six!)
months to improve measurements quality.
It is missing some extra fixes required to bless a stable
release. Chiefly among them, the possiblity of running
cleanly the DNSCheck experiment.
I'm going to work on these issues as soon as possible.
In the meanwhile, this release is a good testing base to check
whether we have additional lingering issues.
A few notes to explain this diff follows.
First, I took the liberty of reducing as much as possible
the amount of markdown linting warning I did see.
Second, 3.11.0-beta.2 is the first release that is fully built
using the cloud. I have not added any PGP key to the cloud
as this seems a bit futile. Maybe it is not and …
=> chore: use ooniprobe-cli 3.11.0-beta.2

package.json, renderer/components/nettests/index.js
This diff uses ooni/probe-cli 3.13.0. I tested that this
specific version was working in linux/amd64.
While there, I noticed that dnscheck was not exposed,
for understandable reasons (it has been broken until the
release of 3.13.0) and exposed it. (It has been quite a
pleasing experience to be able to expose it by just
adding a single line of code for declaring it, well done!)
Reference issue https://github.com/ooni/probe/issues/1843
=> feat: use ooni/probe-cli 3.13.0 and expose dnscheck

renderer/components/dashboard/UrlList.js
Fixes ooni/probe#1848
﻿
Bug introduced because a valid string like `""` was not being used to
initialize a newly added URL input and the length of such a string was
being used in a condition.
=> Fix crash when removing websites in URL editor

renderer/components/nettests/circumvention/RiseupVPN.js, renderer/components/nettests/performance/NDT.js, renderer/components/useRawData.js
Fixes ooni/probe#1953
When the output of `ooniprobe show <id>` fails to return a valid measurement in response, the pages that consume parts of the raw measurement were crashing. This PR fixes that.
First noticed for certain `riseupvpn` tests recently. Fix applied to other places with similar usage.
=> Fix RiseupVPN result screen issue

renderer/components/settings/widgets.js, renderer/pages/settings.js
probe-desktop uses `nettests.websites_enable_max_runtime` from the config and ignores `nettests.websites_max_runtime` when running websites card.
Whereas probe-cli always uses `nettests.websites_max_runtime` (unless it is `0`) to limit the runtime.
This means even if it is disabled in the desktop UI, runtimes are still limited by `probe-cli` because it sees a non-zero value in `config.json`.
The currently proposed solution forces `nettests.websites_max_runtime` to `0` when it is disabled. This loses our ability to remember if the user had previously set a custom duration before disabling.
One way to overcome that would be to store that value in `settings.json` and retrieve it. But I think that adds unnecessaryredundancy.
The ideal solution is probably to move all `probe-desktop` settings …
=> Fix conflict with probe-cli in using max_runtime

test/runtest-all.e2e.js, test/test-results.e2e.js
This fixes some more tests that were broken because of spectron upgrade.
=> Allow some webdriver methods to run on multiple elements in a single call

main/ipcBindings.js, renderer/pages/settings.js
Fixes ooni/probe#2046
There was a race condition with asynchronously writing the values for `nettests.websites_enable_max_runtime` and `nettests.websites_max_runtime`.
In this fix, the functionality is moved to the main process, particularly in the IPC event handler for `config.set` which returns only after synchronously writing the dependent value first. The return value contains the full config with both changes and updates the `ConfigContext` accordingly.
=> Properly sync config values for max_runtime

main/utils/config.js
There was a circular dependency requiring the modules `main/utils/sentry.js` and `main/utils/config.js` from `main/index.js`. This fix breaks it by lazily loading one of the modules when needed.
=> Do not initialize Sentry before initializing config

renderer/components/IntlProvider.js, renderer/components/global.css, renderer/components/globalStyle.js, renderer/pages/_app.js, renderer/pages/_document.js
Fixes ooni/probe#2045
Fixes ooni/probe#1279
Reference issues for font glitch: https://github.com/vercel/next.js/issues/22001 https://github.com/vercel/next.js/issues/18769
This also stops loading unnecessary polyfill for Intl.DisplayNames which reduces the file size of exported pages by ~5mb each.
=> Fix font flickering on page load

package.json
This pull request adds support for using probe-cli v3.15.1 along with the desktop app.
See https://github.com/ooni/probe/issues/2100.
=> desktop: use probe-cli v3.15.1

main/actions.js, main/utils/ooni/ooniprobe.js
Closes https://github.com/ooni/probe/issues/2071
Do we also need to stop autorun at this point?
=> Delete ooni_home_autorun on hard reset

package.json
This diff updates to probe-cli@v3.17.5.
Related issue: https://github.com/ooni/probe/issues/2485.
=> chore: update to ooni/probe-cli@v3.17.5

scripts/download-probe-cli.js
Fixes https://github.com/ooni/probe/issues/2683
I was able to reproduce the issue with windows 11 running on UTM. Windows Defender also raised an alarm when downloading unsigned ooniprobe.exe on it's own - also marking it as a Trojan.
Probe desktop with signed ooniprobe.exe is working as expected on my UTM instance.
=> Sign ooniprobe.exe during build
