renderer/components/Sidebar.js
renderer/components/home/running.js
renderer/components/measurement/MeasurementContainer.js
renderer/components/result/ResultContainer.js
renderer/components/test-results/ResultRow.js
renderer/components/test-results/TestResultsContainer.js
renderer/pages/home.js
renderer/pages/settings.js

Wrap trasnlatable text with FormattedText

---

main/index.js
package.json
yarn.lock

Add ReactDevTools in development env

---

main/index.js
package.json
yarn.lock

This branch adds support for auto-update using electron-builder: https://www.electron.build/auto-update & https://github.com/iffy/electron-updater-example

Add auto-updater support

---

renderer/components/measurement/MeasurementContainer.js
renderer/components/nettests/index.js
renderer/components/nettests/middleboxes/HttpHeaderFieldManipulation.js
renderer/components/nettests/middleboxes/HttpInvalidRequestLine.js
renderer/components/nettests/websites/WebConnectivity.js

Implements views for the two middlebox tests.

Show middlebox measurement details

---

package.json
yarn.lock

These conflicts were introduced in 1dffc3edbc22389fb3deaac4f8dbe12b5252b72f

Fix conflicts in merge with stale auto-update PR

---

renderer/components/nettests/performance/index.js

Change color name from `fuschia` to `fuchsia `
fixes #27

Use corrected name for color fuschia

---

renderer/components/measurement/MeasurementContainer.js
renderer/components/nettests/index.js
renderer/components/nettests/performance/Dash.js
renderer/components/nettests/performance/NDT.js

For NDT and Dash measurements.

Performance measurements screens

---

renderer/components/BackButton.js
renderer/components/test-results/TestResultsContainer.js

This branch adds support for hiding months in the listing that don't have any measurements for them.

Improvements to the result listing

---

renderer/components/test-results/TestResultsContainer.js

Hide results for incomplete tests

---

renderer/components/measurement/RawDataContainer.js

Fixes ooni/probe#987
This also adds a feature that allows closing the container by pressing the 'Esc' key.

Fix issues with Raw Data section on measurements

---

renderer/components/measurement/MeasurementContainer.js

UX improvements to test results detais screens

---

renderer/components/nettests/circumvention/Psiphon.js

Use markdown to format Psiphon measurement summary

---

renderer/components/test-results/ResultRow.js

Align middlebox results

---

package.json
renderer/components/nettests/circumvention/index.js
renderer/pages/home.js
yarn.lock

Add animation when running Circumvention tests

---

renderer/components/ExternalLink.js
renderer/components/Sidebar.js

Fixes ooni/probe#1047
This is how it looks like with the logo in the sidebar.

Add OONIProbe logo to sidebar

---

Readme.md

Fix a Typo in Readme.md

---

.eslintrc.json
.gitignore
package.json
test/dashboard.e2e.js
test/lib/sequencer.js
test/lib/setup.js
test/onboarding.e2e.js
test/sidebar.e2e.js
test/utils.js
yarn.lock

Fixes ooni/probe#1078
* Switched to writing async tests in Jest
* Added custom sequencer to test onboarding process first and also resetting home directory before onboarding.
* Added directory to collect screenshots (maybe there is a way to organize the screenshots)
_Note: The tests themselves are not exhaustive._

Tests in jest

---

main/utils/ooni/run.js

This ensures all logs, even progress ones, are shown in the log view.
Fixes ooni/probe#1039

Log progress to the log too

---

main/utils/ooni/ooniprobe.js
renderer/components/TwoColumnTable.js
renderer/components/result/ResultContainer.js
renderer/components/withIntl.js

Fixes ooni/probe#1043
Fixes ooni/probe#1110

Fix result summary spacing

---

main/index.js
main/windows/aboutWindow.js
renderer/pages/about.js

This fixes: https://github.com/ooni/probe/issues/1096

Auto updater

---

renderer/components/ExternalLink.js
renderer/components/measurement/MethodologyButton.js

Fixes one of the points in ooni/probe#1098

Add icon next to ExternalLink

---

main/actions.js
renderer/components/test-results/ResultRow.js
renderer/components/test-results/TestResultsContainer.js

Handle errors in parsing test results

---

renderer/components/nettests/performance/NDT.js

Fixes ooni/probe#1126
Shows the NDT server hostname provided by the latest `probe-cli`. Since this isn't available in the output of `ooniprobe list <id>`, we additionally fetch the raw measurement using the `useRawData` hook.
Discussed with @bassosimone about using `show` command instead of `list` to render the page. Since such a change will have impact on all measurement screens, I defer it to a separate issue. We also intend to discuss from a broader perspective next week.

Show NDT server hostname correctly

---

renderer/components/Layout.js
renderer/pages/onboard.js

Disable analytics for the onboarding screens

---

CHANGELOG.md
main/index.js
main/utils/config.js
main/utils/ooni/onboard.js
main/windows/aboutWindow.js
package.json
renderer/components/Layout.js
renderer/components/nettests/performance/NDT.js
renderer/pages/about.js
renderer/pages/onboard.js

Closes ooni/probe#1125
This update will include changes from this epic: ooni/probe#1125
Fixes ooni/probe#1124

Release 3.0.1

---

package.json
renderer/components/measurement/MeasurementContainer.js

Show measurements in local timezone

---

main/index.js

Fix logic in looking for informed consent in config file

---

package.json

Part of https://github.com/ooni/probe-engine/issues/828

package.json: use ooni/probe-cli@v3.0.6

---

renderer/components/RightArrow.js
renderer/components/Sidebar.js
renderer/components/formatBitrate.js
renderer/components/formatSpeed.js
renderer/components/result/StatsOverview.js

Fix app crash when viewing results of stopped tests

---

renderer/components/onboard/Sections.js

Fix center alignment of LetsGo button in onboarding

---

package.json

Part of https://github.com/ooni/probe-engine/issues/871

package.json: use ooni/probe-cli@v3.0.7

---

renderer/components/home/running.js

Fixes ooni/probe#1253
There was some left over code from #169

Fix bug in checking animation data validity

---

package.json

Please note that we should merge #178 first before any releases.

package.json: use ooni/probe-cli@v3.0.8

---

package.json

See https://github.com/ooni/probe-engine/issues/972

update: ooni/probe-engine v3.0.9

---

package.json

See https://github.com/ooni/probe-engine/issues/1004

chore: use probe-cli 3.0.10

---

package.json

Part of https://github.com/ooni/probe-engine/issues/1043

chore: use ooni/probe-cli 3.1.0

---

package.json

See https://github.com/ooni/probe-engine/issues/1125

chore(package.json): use ooni/probe-cli 3.2.0

---

package.json

Part of https://github.com/ooni/probe-engine/issues/1181

chore: use ooni/probe-cli v3.5.1

---

renderer/components/measurement/MeasurementContainer.js
renderer/components/nettests/performance/NDT.js

Showing timestamp and network name

Make NDT measurement hero look similar to others

---

Readme.md

At line 19, Changed from "**OONI Probe is free and open source software designed to measure internet**" 
To 
"**OONI Probe is a  free and open source software designed to measure internet**"

Minor grammar fix

---

.github/workflows/ci.yml
package.json
scripts/download-bin.js

See https://github.com/ooni/probe/issues/1468

feat: use ooni/probe-cli v3.10.0-beta.3

---

package.json
renderer/components/result/MeasurementRow.js
renderer/components/result/ResultContainer.js
yarn.lock

Fixes ooni/probe#1683
Fixes ooni/probe#1454

Fix jumpy measurement list

---

package.json
renderer/components/onboard/QuizSteps.js
renderer/components/onboard/__tests__/QuizSteps.test.js
renderer/components/onboard/__tests__/Sections.test.js
renderer/components/onboard/__tests__/Stepper.test.js
renderer/components/onboard/__tests__/__snapshots__/Sections.test.js.snap
renderer/components/onboard/__tests__/__snapshots__/Stepper.test.js.snap
test/lib/setupTests.js
yarn.lock

I'm currently trying to write tests that simulate how a user would interact with that component. I'm not sure if this is the correct/desired way. Kindly review @sarathms 
* I haven't written tests for `QuizSteps.js` and Screen 3 (Crash Reporting) of `Sections.js` component yet because of some hurdles. Getting to the solution of either of the two will solve it for both. 
* For `Stepper.js`, I figured writing snapshot tests makes the most sense
* I think writing some functions in a different file and importing them will be a good idea, for example `rgbToHex()` or `renderComponent()`. I thought of creating a `utils` directory to store such functions, but felt I should ask you first. Kindly provide suggestion.

Component tests for Sections.js, QuizSteps.js and Stepper.js

---

main/index.js
package.json
yarn.lock

Fix broken autoupdate

---

main/utils/config.js

The change was accidentally committed in #231

Fix accidentally changed config file path variable name

---

package.json

See https://github.com/ooni/probe/issues/1843

chore(package.json): use ooni/probe-cli 3.13.0-beta

---

main/utils/ooni/ooniprobe.js
package.json
renderer/components/nettests/experimental/index.js
renderer/components/nettests/index.js

Reference issue: https://github.com/ooni/probe/issues/1917

feat: add support for torsf

---

renderer/components/langUtils.js
test/lib/sequencer.js
test/localization.e2e.js
test/utils.js

Fix bug in falling back to en locale correctly

---

.github/workflows/ci.yml
package.json
renderer/components/utils.js
test/lib/sequencer.js
test/runtest-all.e2e.js
test/runtest-individual.e2e.js
test/test-results.e2e.js

Where applicable, also re-enable torsf.
See https://github.com/ooni/probe/issues/1845.

chore: use probe-cli 3.14.0-beta

---

package.json

See https://github.com/ooni/probe/issues/1845

chore: use ooni/probe-cli v3.14.1

---

renderer/components/__tests__/Sidebar.test.js
renderer/components/dashboard/Logs.js
renderer/components/dashboard/__tests__/Logs.test.js
renderer/components/dashboard/__tests__/running.test.js
renderer/components/dashboard/running.js

Autoscrolling container for logs when running tests

---

main/windows/index.js

Increase window height in Windows to show the test running screen fully

---

main/windows/aboutWindow.js
package.json
renderer/components/formatSpeed.js

Release [v3.7.0](https://github.com/ooni/probe-desktop/releases/tag/v3.7.0)

Release v3.7.0

---

renderer/components/nettests/experimental/index.js

Added text changes + links
Closes https://github.com/ooni/probe/issues/2044

Experimental card improvements

---

renderer/pages/about.js

Closes https://github.com/ooni/probe/issues/2109

Show Probe CLI version in About view

---

Readme.md
package.json

While there, remove obviously misplaced `$` in the README.

package.json: add packonly:linux subcommand

---

package.json

See https://github.com/ooni/probe/issues/2377

chore: use engine@3.16.7

---

package.json
yarn.lock

https://github.com/ooni/probe-desktop/issues/344

Add dependency resolutions for loader-utils and fsevents
